language: dart
dart:
  - stable

env:
  global:
    - FLUTTER_GITHUB=https://github.com/flutter/flutter.git
    - FLUTTER=../flutter/bin/flutter
    - APP=ci_automation
install:
  - git clone $FLUTTER_GITHUB -b stable ../flutter 
  - $FLUTTER doctor
  - $FLUTTER pub get

jobs:
  include:
    - stage: Lint and Unit tests
      script:
        - $FLUTTER analyze
        - $FLUTTER test
    
    - stage: Android Integration Tests
      language: android
      dist: trusty
      android:
        components:
          - tools
          - platform-tools
          - build-tools-25.0.3
          - android-24
          - android-22
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - sys-img-armeabi-v7a-android-22
      licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      before_install:
        - yes | sdkmanager "platforms;android-28"
        - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 32M
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - adb devices
        - adb shell input keyevent 82 &
      script:
        - $FLUTTER --version
        - $FLUTTER doctor
        - cd $APP
        - $FLUTTER devices
        - $FLUTTER driver --target=test_driver/app.dart