os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test 
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable ../flutter 
  - ../flutter/bin/flutter doctor
script:
  - ../flutter/bin/flutter analyze
  - ../flutter/bin/flutter test
  - ../flutter/bin/flutter drive --target=test_driver/app.dart
# cache:
#   directories:
#     - $HOME/.pub-cache
